use_frameworks!

platform :ios, '8.0'

target 'GraphNotifications_Example' do
  pod 'GraphNotifications', :path => '../'

  target 'GraphNotifications_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
