pool:
  name: Project Rome
  demands: sh

steps:
- task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
  displayName: 'Checkout sources'
  inputs:
    script:
     git checkout --progress --force $PARENTCOMMITID 
     gem install cocoapods
     

- task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
  displayName: Build
  inputs:
    script:
      set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GraphNotifications.xcworkspace -scheme GraphNotifications-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
      pod lib lint

- task: PublishTestResults@1
  displayName: 'Publish Test Results'
  inputs:
    testRunner: VSTest
    testResultsFiles: '_build/sim/test/tdd/runners/ios/Debug-iphonesimulator/*.trx'
  condition: succeededOrFailed()
